wip credit problem
ramsha07/cs50 pull request #3
Opened 2023-05-12 07:49 UTC by ramsha07

Credit problem

2023-05-12 08:02 UTC, syedqasimahmed commented on week1/credit/credit.c
> +    long number = 1234;
cardNumber

2023-05-12 08:02 UTC, syedqasimahmed commented on week1/credit/credit.c
> +    int multiply1;
remove this

2023-05-12 08:02 UTC, syedqasimahmed commented on week1/credit/credit.c
> +    int multiply;
remove this

2023-05-12 08:02 UTC, syedqasimahmed commented on week1/credit/credit.c
> +    int multiply2;
remove this

2023-05-12 08:02 UTC, syedqasimahmed commented on week1/credit/credit.c
> +    }
Modify Logic
```javascript 
while (number > 0) {
int firstDigit = number % 10;// 4 
number = number / 10; // 123
int secondDigit = number % 10  *2 ; 

// Logic for second Digit 
sum = sum + secondDigit % 10; 
secondDigit = secondDigit / 10 ; 
sum = sum + secondDigit % 10;  

//  Add firstDigit also in the sum 
sum = sum + firstDigit ;

// In the last line divide number again

number = number /10;

}

```

2023-05-12 10:41 UTC, ramsha07 commented
Please check the updated version

2023-05-12 11:04 UTC, syedqasimahmed requested changes

2023-05-12 11:04 UTC, syedqasimahmed commented on week1/credit/credit.c
> +        printf("Valid\n");
Un necessory printf statement

2023-05-12 11:04 UTC, syedqasimahmed commented on week1/credit/credit.c
> +            int firstTwodigit = 0;
It should be camel case `firstTwoDigit`

2023-05-12 11:04 UTC, syedqasimahmed commented on week1/credit/credit.c
> +    long cardNumber = 378282246310005;
replace it and take user Input

2023-05-12 11:04 UTC, syedqasimahmed commented on week1/credit/credit.c
> +    else
There is common practice if return 
```javascript
if (sum % 10 != 0) {
printf("Valid\n");
return 0;
}
// rest of the code 
while (cardNumber > 0)
        { 
        ....
        }
```

2023-05-12 11:04 UTC, syedqasimahmed commented on week1/credit/credit.c
> +        sum = sum + secondDigit % 10;
these two lines modified by this `sum = sum + secondDigit / 10;`
so we have a cleaner version of this

2023-05-12 11:04 UTC, syedqasimahmed commented on week1/credit/credit.c
> +                else if ((firstTwodigit == 51) || (firstTwodigit == 52) || (firstTwodigit == 53) || (firstTwodigit == 54) || (firstTwodigit == 55))
this condition could be change by `    else if (firstTwoDigits >= 51 && firstTwoDigits <= 55)`

2023-05-12 11:06 UTC, syedqasimahmed commented
@ramsha07 Looks like the direction we want!

2023-05-12 11:27 UTC, ramsha07 commented on week1/credit/credit.c
> +        printf("Valid\n");
i know it is unnecessary, it is just to confirm valid or invalid

2023-05-14 06:56 UTC, ramsha07 commented on week1/credit/credit.c
> +    else
remove else

2023-05-14 06:56 UTC, ramsha07 commented on week1/credit/credit.c
> +            int firstTwoDigit = 0;
Define this with other variables. i.e (head of main)

2023-05-14 06:56 UTC, ramsha07 commented on week1/credit/credit.c
> +        }
Modify logic 
while loop only resposible for counting `cardLength` and `firstTwoDigit`. Rest of the logic should be move out from while loop.

Another thing is compare card length as well with the starting digit.

2023-05-14 06:56 UTC, ramsha07 commented on week1/credit/credit.c
> +                }
ADD one else with this if-else chain which prints INVALID

2023-05-14 07:11 UTC, ramsha07 commented on week1/credit/credit.c
> +    long number = cardNumber;
variable names should make sense.  (Optional)

2023-05-14 07:11 UTC, ramsha07 commented on week1/credit/credit.c
> +    int sum = 0;
This variable name should be changed to `sumOfCardDigits` or `total` think a better name for this. (Optional)

2023-05-14 07:11 UTC, ramsha07 commented on week1/credit/credit.c
> +                else if ((firstTwoDigit >= 51) && (firstTwoDigit <= 55))
un necessory brackets should be removed and looks like this.

`else if (firstTwoDigit >= 51 && firstTwoDigit <= 55)`

2023-05-14 07:11 UTC, ramsha07 commented on week1/credit/credit.c
> +        sum = sum + secondDigit / 10;
these two line can be simplified as 
```javascript
    sum = sum + secondDigit % 10  + secondDigit / 10; 
    ```

2023-05-14 16:39 UTC, syedqasimahmed approved these changes

2023-05-14 16:40 UTC, syedqasimahmed commented
@ramsha07  Could you please rename the PR title and remove WIP: also merge this PR.

2023-05-14 16:42 UTC, merged